export const siteConfig = {
  name: "Nexora",
  description: "Architecting Digital Dominance with Next.js 16 Performance.",
  contact: {
    email: "contact@nexora.in",
    address: "Roorkee, Haridwar, Uttarakhand, India",
    phone: "+91 0000000000",
    whatsapp: "https://wa.me/910000000000",
    twitter: "https://twitter.com/nexora",
    linkedin: "https://linkedin.com/company/nexora",
    github: "https://github.com/nexora",
  },
  nav: [
    { title: "Home", href: "/" },
    { title: "About", href: "/about" },
    { title: "Services", href: "/services" },
    { title: "Products", href: "/products" },
    { title: "Contact", href: "/contact" },
  ],
  sections: {
    hero: {
      line1: "Get More Customers with",
      highlight: "Modern Websites",
      line2: "Built for Your Business",
      description: "Professional & Affordable websites for local businesses. Live in 3–5 days.",
      socialProof: "Trusted by Local Businesses",
    },
    services: {
      title: "Solutions for High-Stake Startups",
      subtitle: "Our Ecosystem",
      description: "We provide lethal technical superiority to help your startup dominate its market, from ideation to exit.",
    },
    products: {
      title: "Battle-Tested Assets",
      subtitle: "The Forge",
      description: "Ready-to-deploy Next.js 16 templates designed to crush your competition.",
    },
    testimonials: {
      title: "What Founders Say",
      subtitle: "Performance Logs",
      description: "Validated by high-growth companies worldwide.",
    },
    process: {
      title: "Synchronized Growth Path",
      subtitle: "The Pipeline",
      description: "A lean, transparent execution framework for zero-latency product delivery.",
    },
    portfolio: {
      title: "Mission History",
      subtitle: "Field Results",
      description: "A compilation of high-impact deployments delivered with Nexora precision.",
    },
    contact: {
      title: "Initiate Deployment",
      subtitle: "Command Center",
      description: "Establish a secure connection with our technical response team.",
    },
    cta: {
      title: "Ready to dominate your sector?",
      description: "Join the elite cohort of companies scaling with Nexora. Neutralize complexity today.",
      buttonText: "Initiate Project",
      secondaryButtonText: "Mission Briefing",
    },
    faq: {
      title: "Intelligence Briefing",
      subtitle: "FAQ",
      description: "Core inquiries answered with tactical precision.",
    },
    about: {
      title: "About",
      subtitle: "The Mission",
      description: "We are an elite squad building technical foundations for the next billion-dollar ventures.",
      mission: "Nexora decodes complexity, empowering founders with absolute technical leverage in a saturated market.",
      vision: "To be the gold standard for high-performance digital engineering and strategic growth.",
      valuesTitle: "Core Doctrines",
      valuesSubtitle: "Absolute Values",
      valuesDescription: "The principles that drive our dominance.",
    },
  },
  stats: [
    { label: "Ventures", value: "500+" },
    { label: "Founders", value: "10k+" },
    { label: "Assets", value: "50+" },
    { label: "Regions", value: "20+" },
  ],
  faqs: [
    {
      q: "Is Nexora free to use?",
      a: "Begin with our tactical tier and scale into premium infrastructure as you grow.",
    },
    {
      q: "Who is this platform for?",
      a: "Visionary founders and elite engineers demanding zero-compromise digital assets.",
    },
    {
      q: "How do I get started?",
      a: "Select a high-performance asset from The Forge or initiate a custom brief.",
    },
    {
      q: "Is deployment secure?",
      a: "Yes. All assets are audited for security and architected with modern encryption standards.",
    },
  ],
  values: [
    {
      title: "Technical Excellence",
      description: "Next.js 16 precision in every line of code.",
      icon: "Zap",
    },
    {
      title: "Absolute Security",
      description: "Hardened infrastructure for mission-critical data.",
      icon: "ShieldCheck",
    },
    {
      title: "Strategic Impact",
      description: "Built for founders, not followers.",
      icon: "Users",
    },
  ],
  services: [
    {
      id: "web-dev",
      title: "Next.js 16 Engineering",
      description: "High-performance, instant-navigation web applications built with the latest architectural patterns.",
      icon: "Code",
    },
    {
      id: "ui-ux",
      title: "High-Fidelity Design",
      description: "Human-centric interfaces that maximize conversion and brand authority.",
      icon: "Palette",
    },
    {
      id: "cloud",
      title: "Cloud Infrastructure",
      description: "Scale from 0 to 1 million users with zero-latency cloud deployments.",
      icon: "Cloud",
    },
    {
      id: "marketing",
      title: "Growth Engineering",
      description: "Data-driven systems to aggressively scale your presence and user base.",
      icon: "BarChart",
    },
    {
      id: "consulting",
      title: "Technical Strategy",
      description: "Direct elite consulting on tech stacks and strategic product roadmaps.",
      icon: "MessageSquare",
    },
    {
      id: "mobile-dev",
      title: "Native Mobile Systems",
      description: "Synchronized cross-platform solutions for iOS and Android dominance.",
      icon: "Smartphone",
    },
  ],
  products: [
    {
      id: "pro-template-1",
      title: "SaaS Dashboard Kit",
      description: "Ultra-fast Next.js 16 dashboard system for data-heavy startups.",
      longDescription: "The most advanced dashboard ecosystem ever built. Architected with Next.js 16 Instant Navigations, Server Actions, and a precision-engineered dark mode system. Built for founders who refuse to compromise on latency.",
      price: "₹4,999",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
      category: "Templates",
      features: ["Next.js 16 Instant Navs", "Turbopack Optimized", "Full TypeScript Core", "Advanced Data Viz", "Auth.js Ready"],
    },
    {
      id: "pro-template-2",
      title: "E-commerce Starter",
      description: "The ultimate boilerplate for high-conversion online stores.",
      longDescription: "Stop building from scratch and start selling in hours. Our E-commerce starter is architected for speed, conversion, and architectural purity. Includes a high-performance checkout flow, inventory management, and multi-currency support out of the box.",
      price: "₹7,999",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
      category: "Boilerplate",
      features: ["Stripe Integration", "PostgreSQL & Prisma", "Framer Motion Animations", "SEO Optimized Pages", "Admin Management Suite"],
    },
    {
      id: "pro-template-3",
      title: "Portfolio Pro",
      description: "Showcase your work with style using this premium portfolio template.",
      longDescription: "The ultimate weapon for creatives and developers who want to stand out. Portfolio Pro combines high-end cinematic animations with a brutalist layout that puts your work front and center. Built for maximum lighthouse scores and zero-latency navigations.",
      price: "₹2,499",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop",
      category: "Templates",
      features: ["3D Tilt Effects", "Magnetic UI Components", "Dynamic Blog Logic", "Responsive Case Studies", "Interactive Contact Form"],
    },
    {
      id: "pro-template-4",
      title: "AI Chat Interface",
      description: "A luxury UI boilerplate for building advanced AI-powered chat applications.",
      longDescription: "The future is conversational. Our AI Chat Interface provides the most fluid, reactive, and visually stunning backdrop for your LLM-powered products. Optimized for streaming responses and high-fidelity message rendering.",
      price: "₹5,999",
      image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop",
      category: "Boilerplate",
      features: ["Streaming Response UI", "Markdown & Code Highlighting", "Voice Interaction Support", "Vector Database Ready", "Custom Theme Engine"],
    },
    {
      id: "pro-template-5",
      title: "Fintech Mobile Pack",
      description: "Over 50+ premium mobile screens for banking and investment apps.",
      longDescription: "The gold standard for mobile finance design. This pack includes everything from biometric authentication screens to complex multi-layer investment charts. Designed with extreme attention to security and usability patterns.",
      price: "₹9,999",
      image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=2070&auto=format&fit=crop",
      category: "UI Kit",
      features: ["50+ Figma-matched Screens", "Native iOS & Android Feel", "Financial Chart Library", "Security Pattern Flows", "Dark & Light Mode Experts"],
    },
    {
      id: "pro-template-6",
      title: "Logistics Dashboard",
      description: "Complex data visualization and tracking system for logistics startups.",
      longDescription: "Master the global supply chain with our specialized Logistics Dashboard. Featuring real-time map tracking, complex fleet management interfaces, and sophisticated data visualization for mission-critical operations.",
      price: "₹6,499",
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070&auto=format&fit=crop",
      category: "Templates",
      features: ["Real-time Map Integration", "Fleet Management UI", "Supply Chain Analytics", "Automated Reporting", "High-Load Data Handling"],
    },
  ],
  testimonials: [
    {
      id: "1",
      name: "Arnav Gupta",
      company: "TechFlow Solutions",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=150&h=150&fit=crop",
      quote: "Nexora modernized our online presence completely. The speed and design are world-class.",
    },
    {
      id: "2",
      name: "Priya Sharma",
      company: "Bloom Boutique",
      avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=150&h=150&fit=crop",
      quote: "My boutique's sales increased significantly after launching our new website with Arnav's help.",
    },
    {
      id: "3",
      name: "Rajesh Kumar",
      company: "Kumar Sweets & Cafe",
      avatar: "https://images.unsplash.com/photo-1520341280432-4749d4d7bcf9?q=80&w=150&h=150&fit=crop",
      quote: "Transparent pricing and excellent support. Best choice for any local business in Roorkee.",
    },
  ],
  process: [
    {
      title: "Discovery",
      description: "We dive deep into your goals, audience, and market to define the project scope.",
      icon: "Lightbulb",
    },
    {
      title: "Design",
      description: "Our designers create wireframes and high-fidelity mockups of your vision.",
      icon: "Palette",
    },
    {
      title: "Development",
      description: "Our engineers build your product using the latest technologies and best practices.",
      icon: "Code",
    },
    {
      title: "Launch",
      description: "We conduct final testing and deploy your product to the world.",
      icon: "Rocket",
    },
  ],
  portfolio: [
    {
      id: "1",
      title: "EcoDrive Dashboard",
      category: "SaaS",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "2",
      title: "Lumina Mobile App",
      category: "Mobile",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
    },
    {
      id: "3",
      title: "FinStream Platform",
      category: "Fintech",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "4",
      title: "Vortex Analytics",
      category: "Big Data",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "5",
      title: "Nexus NFT Market",
      category: "Web3",
      image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "6",
      title: "Aura Smart Home",
      category: "IoT",
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    },
  ],
};

export type SiteConfig = typeof siteConfig;
