export const siteConfig = {
  name: "Nexora",
  description: "Building Tech, Powering Media, Creating Products.",
  contact: {
    email: "hello@nexora.io",
    address: "Global / remote",
    phone: "+1 (555) 000-0000",
    whatsapp: "https://wa.me/15550000000",
    twitter: "https://twitter.com/nexora",
    linkedin: "https://linkedin.com/company/nexora",
    github: "https://github.com/nexora",
  },
  nav: [
    { title: "Home", href: "/" },
    { title: "About", href: "/about" },
    { title: "Services", href: "/services" },
    { title: "Products", href: "/products" },
    { title: "Contact", href: "/contact" },
  ],
  sections: {
    hero: {
      line1: "Engineering",
      highlight: "Digital",
      line2: "Dominance",
      description: "Building Tech, Powering Media, Creating Products with absolute technical superiority.",
      socialProof: "50+ founders joined",
    },
    services: {
      title: "Solutions for Every Stage",
      subtitle: "Our Services",
      description: "We provide comprehensive digital solutions to help your startup scale, from initial ideation to global expansion.",
    },
    products: {
      title: "Premium Assets for Scale",
      subtitle: "Our Products",
      description: "Ready-to-use templates and boilerplates designed to kickstart your next big thing.",
    },
    testimonials: {
      title: "What Foundations Say",
      subtitle: "Success Stories",
      description: "Join hundreds of founders who have accelerated their growth with our platform.",
    },
    process: {
      title: "How We Build Progress",
      subtitle: "Our Process",
      description: "A streamlined, transparent approach to taking your vision from concept to reality.",
    },
    portfolio: {
      title: "Our Recent Successes",
      subtitle: "Portfolio",
      description: "A selection of high-impact projects we've delivered for our partners.",
    },
    contact: {
      title: "Let's Build Something Great",
      subtitle: "Contact Us",
      description: "Ready to take your startup to the next level? Get in touch with our team today.",
    },
    cta: {
      title: "Ready to launch your vision?",
      description: "Join hundreds of successful companies already scaling with our platform. Start your project today.",
      buttonText: "Start Project",
      secondaryButtonText: "Talk to Expert",
    },
    faq: {
      title: "Frequently Asked Questions",
      subtitle: "Got questions?",
      description: "We've answered the most common queries.",
    },
    about: {
      title: "About",
      subtitle: "Our Story",
      description: "We are building smart solutions to simplify digital growth and empower founders.",
      mission: "At Nexora, we aim to simplify how businesses manage their digital footprint, products, and daily growth operations.",
      vision: "Our platform helps companies become more efficient, connected, and data-driven in a competitive landscape.",
      valuesTitle: "Our Values",
      valuesSubtitle: "What drives us",
      valuesDescription: "Core principles behind Nexora",
    },
  },
  stats: [
    { label: "Schools", value: "500+" },
    { label: "Users", value: "10k+" },
    { label: "Products", value: "50+" },
    { label: "Countries", value: "20+" },
  ],
  faqs: [
    {
      q: "Is Nexora free to use?",
      a: "Yes, you can start with our free plan and upgrade anytime to access premium features.",
    },
    {
      q: "Who is this platform for?",
      a: "Founders, designers, and developers looking to accelerate their product launch.",
    },
    {
      q: "How do I get started?",
      a: "Simply browse our products or contact our expert team to discuss your project.",
    },
    {
      q: "Is payment secure?",
      a: "Yes, all transactions are secured with industry-standard payment gateways.",
    },
  ],
  values: [
    {
      title: "Innovation",
      description: "We build modern solutions for real problems.",
      icon: "Zap",
    },
    {
      title: "Security",
      description: "Your data is safe and protected by elite standards.",
      icon: "ShieldCheck",
    },
    {
      title: "Community",
      description: "Built for founders, designers, and visionaries.",
      icon: "Users",
    },
  ],
  services: [
    {
      id: "web-dev",
      title: "Web Development",
      description: "Custom, high-performance web applications built with modern frameworks like Next.js and React.",
      icon: "Code",
    },
    {
      id: "ui-ux",
      title: "UI/UX Design",
      description: "User-centric interface designs that prioritize usability and brand identity.",
      icon: "Palette",
    },
    {
      id: "cloud",
      title: "Cloud Infrastructure",
      description: "Scalable and secure cloud solutions to power your digital products.",
      icon: "Cloud",
    },
    {
      id: "marketing",
      title: "Digital Marketing",
      description: "Data-driven strategies to grow your online presence and customer base.",
      icon: "BarChart",
    },
    {
      id: "consulting",
      title: "Tech Consulting",
      description: "Expert advice on technology stacks and product roadmap planning.",
      icon: "MessageSquare",
    },
    {
      id: "mobile-dev",
      title: "Mobile Apps",
      description: "Native and cross-platform mobile solutions for iOS and Android.",
      icon: "Smartphone",
    },
  ],
  products: [
    {
      id: "pro-template-1",
      title: "SaaS Dashboard Kit",
      description: "A comprehensive UI kit for building modern SaaS dashboards quickly.",
      longDescription: "Elevate your enterprise applications with the most advanced dashboard system ever built for Next.js. Featuring over 100+ precision-crafted components, 5 unique dashboard layouts, and a fully integrated dark mode system that adheres to elite design standards.",
      price: "$49",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
      category: "Templates",
      features: ["100+ Premium Components", "Next.js 14 App Router", "Full TypeScript Support", "Chart.js & Recharts Integration", "Auth.js Ready"],
    },
    {
      id: "pro-template-2",
      title: "E-commerce Starter",
      description: "The ultimate boilerplate for high-conversion online stores.",
      longDescription: "Stop building from scratch and start selling in hours. Our E-commerce starter is architected for speed, conversion, and architectural purity. Includes a high-performance checkout flow, inventory management, and multi-currency support out of the box.",
      price: "$79",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
      category: "Boilerplate",
      features: ["Stripe Integration", "PostgreSQL & Prisma", "Framer Motion Animations", "SEO Optimized Pages", "Admin Management Suite"],
    },
    {
      id: "pro-template-3",
      title: "Portfolio Pro",
      description: "Showcase your work with style using this premium portfolio template.",
      longDescription: "The ultimate weapon for creatives and developers who want to stand out. Portfolio Pro combines high-end cinematic animations with a brutalist layout that puts your work front and center. Built for maximum lighthouse scores and zero-latency navigations.",
      price: "$29",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop",
      category: "Templates",
      features: ["3D Tilt Effects", "Magnetic UI Components", "Dynamic Blog Logic", "Responsive Case Studies", "Interactive Contact Form"],
    },
    {
      id: "pro-template-4",
      title: "AI Chat Interface",
      description: "A luxury UI boilerplate for building advanced AI-powered chat applications.",
      longDescription: "The future is conversational. Our AI Chat Interface provides the most fluid, reactive, and visually stunning backdrop for your LLM-powered products. Optimized for streaming responses and high-fidelity message rendering.",
      price: "$59",
      image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?q=80&w=2070&auto=format&fit=crop",
      category: "Boilerplate",
      features: ["Streaming Response UI", "Markdown & Code Highlighting", "Voice Interaction Support", "Vector Database Ready", "Custom Theme Engine"],
    },
    {
      id: "pro-template-5",
      title: "Fintech Mobile Pack",
      description: "Over 50+ premium mobile screens for banking and investment apps.",
      longDescription: "The gold standard for mobile finance design. This pack includes everything from biometric authentication screens to complex multi-layer investment charts. Designed with extreme attention to security and usability patterns.",
      price: "$99",
      image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?q=80&w=2070&auto=format&fit=crop",
      category: "UI Kit",
      features: ["50+ Figma-matched Screens", "Native iOS & Android Feel", "Financial Chart Library", "Security Pattern Flows", "Dark & Light Mode Experts"],
    },
    {
      id: "pro-template-6",
      title: "Logistics Dashboard",
      description: "Complex data visualization and tracking system for logistics startups.",
      longDescription: "Master the global supply chain with our specialized Logistics Dashboard. Featuring real-time map tracking, complex fleet management interfaces, and sophisticated data visualization for mission-critical operations.",
      price: "$69",
      image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?q=80&w=2070&auto=format&fit=crop",
      category: "Templates",
      features: ["Real-time Map Integration", "Fleet Management UI", "Supply Chain Analytics", "Automated Reporting", "High-Load Data Handling"],
    },
  ],
  testimonials: [
    {
      id: "1",
      name: "Alex Rivers",
      company: "Orbit Tech",
      avatar: "https://i.pravatar.cc/150?u=alex",
      quote: "Nexora transformed our vision into a stunning reality. Their attention to detail is unmatched.",
    },
    {
      id: "2",
      name: "Sarah Chen",
      company: "Lumina Apps",
      avatar: "https://i.pravatar.cc/150?u=sarah",
      quote: "Working with the Nexora team was the best decision we made for our launch.",
    },
    {
      id: "3",
      name: "Michael Ross",
      company: "FinStream",
      avatar: "https://i.pravatar.cc/150?u=michael",
      quote: "Fast, professional, and highly skilled. Highly recommended for any startup.",
    },
  ],
  process: [
    {
      title: "Discovery",
      description: "We dive deep into your goals, audience, and market to define the project scope.",
      icon: "Lightbulb",
    },
    {
      title: "Design",
      description: "Our designers create wireframes and high-fidelity mockups of your vision.",
      icon: "Palette",
    },
    {
      title: "Development",
      description: "Our engineers build your product using the latest technologies and best practices.",
      icon: "Code",
    },
    {
      title: "Launch",
      description: "We conduct final testing and deploy your product to the world.",
      icon: "Rocket",
    },
  ],
  portfolio: [
    {
      id: "1",
      title: "EcoDrive Dashboard",
      category: "SaaS",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "2",
      title: "Lumina Mobile App",
      category: "Mobile",
      image: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?q=80&w=2426&auto=format&fit=crop",
    },
    {
      id: "3",
      title: "FinStream Platform",
      category: "Fintech",
      image: "https://images.unsplash.com/photo-1542744173-8e7e53415bb0?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "4",
      title: "Vortex Analytics",
      category: "Big Data",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "5",
      title: "Nexus NFT Market",
      category: "Web3",
      image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?q=80&w=2070&auto=format&fit=crop",
    },
    {
      id: "6",
      title: "Aura Smart Home",
      category: "IoT",
      image: "https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=2070&auto=format&fit=crop",
    },
  ],
};

export type SiteConfig = typeof siteConfig;
